version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupword
    - dupl
    - embeddedstructfieldcheck
    - errcheck
    - errname
    - exptostd
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - iotamixing
    - lll
    - maintidx
    - misspell
    - mnd
    - nakedret
    - nilnesserr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
  settings:
    mnd:
      checks:
        - case
        - condition
        - return
    revive:
      rules:
        - name: var-declaration
          disabled: true
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: comment-spacings
    embeddedstructfieldcheck:
      empty-line: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
